# Generated by Django 4.2.2 on 2023-06-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile_no_pic.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='croupieruser',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='croupier_room', to='rooms.room'),
        ),
    ]
