# Generated by Django 4.2.2 on 2023-06-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0002_alter_baseuser_profile_pic_alter_croupieruser_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croupieruser',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='croupier_room', to='rooms.room'),
        ),
    ]
