# Generated by Django 4.2.2 on 2023-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_roomplayer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile_no_pic.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
