# Generated by Django 4.2.2 on 2023-07-06 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_baseuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giocata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('importo', models.FloatField()),
                ('is_ricarica', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giocate', to='users.playeruser')),
            ],
        ),
    ]
