# Generated by Django 4.2.2 on 2023-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_giocata'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocata',
            name='room',
            field=models.CharField(default='', max_length=255),
        ),
    ]
