# Generated by Django 4.2.2 on 2023-07-11 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_baseuser_date_joined_alter_baseuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 8, 59, 45, 784446, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 8, 59, 45, 784446, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='giocata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 8, 59, 45, 801736, tzinfo=datetime.timezone.utc)),
        ),
    ]
