# Generated by Django 4.2.2 on 2023-07-14 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_baseuser_date_joined_alter_baseuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 11, 43, 1, 342302, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 11, 43, 1, 342302, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
