# Generated by Django 4.2.2 on 2023-08-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_baseuser_date_joined_alter_baseuser_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giocata',
            options={'verbose_name': 'giocata', 'verbose_name_plural': 'giocate'},
        ),
    ]
