# Generated by Django 4.2.2 on 2023-06-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, unique=True)),
                ('seats_number', models.IntegerField()),
                ('minimum_bet', models.CharField(choices=[('0.10', '0.10'), ('0.20', '0.20'), ('0.50', '0.50'), ('1.00', '1.00'), ('2.00', '2.00'), ('5.00', '5.00'), ('10.00', '10.00'), ('20.00', '20.00'), ('50.00', '50.00'), ('100.00', '100.00'), ('200.00', '200.00'), ('500.00', '500.00')], max_length=10)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('seats_occupied', models.IntegerField(default=0)),
                ('cover_pic', models.ImageField(blank=True, default='room_thumbnail/room_no_thumb.png', upload_to='icon_1/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.section')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_name'],
            },
        ),
    ]
