# Generated by Django 4.2.2 on 2023-08-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cover_pic',
            field=models.ImageField(blank=True, default='icon_1/room_thumbnail/room_no_thumb.png', upload_to='icon_1/'),
        ),
    ]
