# Generated by Django 4.2.2 on 2023-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cover_pic',
            field=models.ImageField(blank=True, default='room_thumbnail/room_no_thumb.png', upload_to='room_thumbnail/'),
        ),
    ]
